language: go
go:
  - "1.15"

services:
  - mysql
  - postgresql

env:
  - GO111MODULE=on

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS elipzis_test;"
  - mysql -e "GRANT ALL PRIVILEGES ON elipzis_test.* TO 'elipzis'@'localhost' IDENTIFIED BY 'elipzis'"
  - psql -c 'create database elipzis_test;' -U postgres
  - psql -c "CREATE USER elipzis WITH ENCRYPTED PASSWORD 'elipzis'" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE elipzis_test TO elipzis" -U postgres
  - go get -t -v ./...

script:
  - go get -u github.com/goware/modvendor
  - go mod vendor
  - modvendor -copy="**/*.html **/*.js **/*.css **/*.tmpl **/*.ttf **/*.woff **/*.woff2" -v
  - TEST_DB=postgres go test -v ./...
  - TEST_DB=mysql go test -v ./...
